// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projekat.Models;

namespace projekat.Migrations
{
    [DbContext(typeof(RegisterDetailsContext))]
    [Migration("20220227150116_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("projekat.Models.RegisterDetails", b =>
                {
                    b.Property<int>("RegisterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("fullName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("indexNumber")
                        .HasColumnType("int");

                    b.Property<string>("subjectName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("yearNumber")
                        .HasColumnType("int");

                    b.HasKey("RegisterId");

                    b.ToTable("RegisterDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
